### ISSUE TITLE
Invalid index during import

### ISSUE THREAD

**Issue by wiseelf** [opsworks-co/terraform-gitlab#1]
```╷
│ Error: Invalid index
│
│   on .terraform/modules/gitlab_resources/main.tf line 635, in locals:
│  635:   subgroup_id_map = { for group in local.subgroups : "${group.parent}/${group.name}" => gitlab_group.subgroups["${group.parent}/${group.name}"].id }
│     ├────────────────
│     │ gitlab_group.subgroups is object with 1 attribute "roles/gitlab-administrators"
│     │ group.name is "project-sre-review"
│     │ group.parent is "roles"
│
│ The given key does not identify an element in this collection value.
```

Issue occurs during import when not imported groups are in the config.

```
groups:
  - name: roles
    create: true
    settings:
      visibility: private
      description: "Parent group for user roles subgroups"

  - name: gitlab-administrators (trying to import)
    create: true
    parent: roles
    settings:
      visibility: private
      description: "Subgroup under roles"
      saml_links:
        - access_level: maintainer
          saml_group_name: "gitlab-administrators"

  - name: project-sre-review (not imported)
    create: true
    parent: roles
    settings:
      visibility: private
      description: "Another subgroup under roles"

```
